# -*- coding: utf-8 -*-
"""taxi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gmRIAjNrUCSs8M3BRURxFcAiu7BIWPq3
"""

import pandas as pd
from geopy.distance import geodesic


url = "https://raw.githubusercontent.com/jeffprosise/Machine-Learning/refs/heads/master/Data/taxi-fares.csv"
df = pd.read_csv(url)


print("Original shape:", df.shape)
df.head()

df.shape

df = df[df['passenger_count']==1]
df = df.drop(['key', 'passenger_count'], axis=1)
df.head()

df.shape

df = df[(df['pickup_longitude'].between(-75,-72))&
        (df['pickup_latitude'].between(40,42))&
        (df['dropoff_longitude'].between(-75,-72))&
        (df['dropoff_latitude'].between(40,42))]

def calculate_distance(row):
  start = (row['pickup_latitude'], row['pickup_longitude'])
  stop = (row['dropoff_latitude'], row['dropoff_longitude'])
  return geodesic(start, stop).miles

df['distance_miles'] = df.apply(calculate_distance, axis=1)
df = df[df['distance_miles'] > 0.1 ]

df

df['pickup_datetime'] = pd.to_datetime(df['pickup_datetime'])
df['hour'] = df['pickup_datetime'].dt.hour
df['day'] = df['pickup_datetime'].dt.dayofweek

df.head()

df = df.drop(['pickup_datetime', 'pickup_longitude','pickup_latitude','dropoff_longitude','dropoff_latitude'], axis = 1 )

df.head()

corr_matrix = df.corr()
corr_matrix["fare_amount"].sort_values(ascending=False)

from sklearn.model_selection import train_test_split

X = df.drop('fare_amount', axis=1).values
y = df['fare_amount'].values
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)

def find_dist(start,stop):
  return geodesic(start, stop).miles

start = 40.7580, -73.9855
end = 40.7075, -74.0113
print(find_dist(start,end))

from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="invoice_app")
lat = 37.6753447
lon = -77.5995365
location = geolocator.reverse((lat, lon))
print(f"Address: {location.address}")
print(f"Coordinates: ({location.latitude}, {location.longitude})")

df

!pip install requests python-dotenv openai

import os
from openai import OpenAI
from dotenv import load_dotenv

os.environ['OPENAI_API_KEY'] ="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"

load_dotenv(override=True)
api_key = os.getenv('OPENAI_API_KEY')


if api_key and api_key.startswith('sk-proj-') and len(api_key) > 10:
    print("API key looks good so far")
else:
    print("There might be a problem with your API key? Please visit the troubleshooting notebook!")

MODEL = 'gpt-4o-mini'
openai = OpenAI()

from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="invoice_app")

import pandas as pd
import os

def log_invoice(data_dict, csv_filename="invoice_log.csv"):
    df = pd.DataFrame([data_dict])

    if os.path.exists(csv_filename):
        existing_df = pd.read_csv(csv_filename)
        df = pd.concat([existing_df, df], ignore_index=True)

    df.to_csv(csv_filename, index=False)
    print(f" Logged invoice to {csv_filename}")

from datetime import datetime

def capture_inputs(name, email, age, datetime_str, pickup_lat, pickup_lon, dropoff_lat, dropoff_lon):
    pickup_cord = (pickup_lat, pickup_lon)
    dropoff_cord = (dropoff_lat, dropoff_lon)

    dt = datetime.strptime(datetime_str, "%Y-%m-%d %H:%M")
    hour = dt.hour
    dayofweek = dt.weekday()


    ride_distance = find_dist(pickup_cord, dropoff_cord)


    X = [[ride_distance, hour, dayofweek]]
    ride_fare = model.predict(X)[0]
    date_str = dt.strftime("%A, %d %B %Y")
    time_str = dt.strftime("%I:%M %p")
    pickup = f"Latitude {pickup_cord[0]:.4f}, Longitude {pickup_cord[1]:.4f}"
    dropoff = f"Latitude {dropoff_cord[0]:.4f}, Longitude {dropoff_cord[1]:.4f}"


    # LOGGING STARTS HERE

    user_data = {
    "name": {name},
    "email": {email},
    "age": {age},
    "date_time": {datetime_str},
    "pickup_cord": {pickup_cord},
    "dropoff_cord": {dropoff_cord},

    "pickup_location": {geolocator.reverse(pickup_cord).address},
    "dropoff_location":{geolocator.reverse(dropoff_cord).address},
    "Distance_Traveled": {ride_distance},
    "Fare_Charged": {ride_fare}}


    log_invoice(user_data)

  # LOGGING ENDS HERE


    prompt = f"""
Generate a professional, friendly taxi invoice for a user with the following details:

- Name: {name}
- Email: {email}
- Age: {age}
- Trip Date: {date_str}
- Trip Time: {time_str}
- Pickup Coordinates: {pickup}
- Dropoff Coordinates: {dropoff}
- Distance Traveled: {ride_distance:.2f} miles
- Fare Charged: ${ride_fare:.2f}
- pickup location: {geolocator.reverse(pickup_cord).address}
- dropoff location: {geolocator.reverse(dropoff_cord).address}

Instructions:
- Include a warm greeting
- Present trip details clearly
- Do provide the fare breakdown. the final fare must be the provided fare plus tax
- Close with a thank-you message from FastCab
- Keep it under 300 words
- Format it like a real invoice document
""".strip()

    return prompt

from IPython.display import display, Markdown

def stream_invoice(prompt):
    system_prompt ="You are a professional invoice generator for a fictional cab company called FastCab. Generate clean, friendly, formatted invoices based on ride details. Keep them under 300 words."

    stream = openai.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt}
        ],
        stream=True
    )

    full_response = ""
    display_handle = display(Markdown("🧾 Generating invoice..."), display_id=True)

    for chunk in stream:
        delta = chunk.choices[0].delta.content if chunk.choices[0].delta else ""
        full_response += delta or ""
        display_handle.update(Markdown(full_response))

    return full_response

!pip install fpdf

!pip install unidecode

from fpdf import FPDF
from unidecode import unidecode

def save_pdf(text, filename="invoice.pdf"):
    clean_text = unidecode(text)

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_font("Arial", size=12)
    pdf.multi_cell(0, 10, clean_text)

    pdf.output(filename)
    return filename

user_prompt = capture_inputs(
    "praxxv",
    "prxv@gmail.com",
    22,
    "2025-07-02 14:30",
    40.75673945371981, -73.99246567424889,
    40.645376886561934, -73.77974484268215
)

invoice_text = stream_invoice(user_prompt)

if invoice_text:
    pdf_path = save_pdf(invoice_text)
    print(f"PDF saved to: {pdf_path}")
else:
    print(" Invoice not generated.")

