# -*- coding: utf-8 -*-
"""fakenews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BVXlwJkbBsPgUckFyHvQuHMf4mpUzUYM
"""

import os
import requests
from IPython.display import Markdown, display, update_display
from openai import OpenAI
from google.colab import drive
from huggingface_hub import login
from google.colab import userdata
from transformers import AutoTokenizer, AutoModelForCausalLM, TextStreamer, BitsAndBytesConfig
import torch

import pandas as pd
import numpy as np

df = pd.read_csv("fake_and_real_news.csv")

df['label'] = df['label'].astype(str).str.strip().map({'Real': 1, 'Fake': 0})
df

