# -*- coding: utf-8 -*-
"""book$.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XdROTGRbkp9KlSWFIIF_ufdCMfMSEIHH
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
books = pd.read_csv('books.csv')
ax = plt.axes()
sns.heatmap(books.isna().transpose(), cbar=False, ax=ax)

plt.xlabel("Columns")
plt.ylabel("Missing values")

plt.show()
books["missing_description"] = np.where(books["description"].isna(), 1, 0)
books["age_of_book"] = 2024 - books["published_year"]
columns_of_interest = ["num_pages", "age_of_book", "missing_description", "average_rating"]

correlation_matrix = books[columns_of_interest].corr(method = "spearman")

sns.set_theme(style="white")
plt.figure(figsize=(8, 6))
heatmap = sns.heatmap(correlation_matrix, annot=True, fmt=".2f", cmap="coolwarm",
                      cbar_kws={"label": "Spearman correlation"})
heatmap.set_title("Correlation heatmap")
plt.show()

book_missing = books[~(books["description"].isna()) &
      ~(books["num_pages"].isna()) &
      ~(books["average_rating"].isna()) &
      ~(books["published_year"].isna())
]
book_missing["categories"].value_counts().reset_index().sort_values("count", ascending=False)

book_missing["words_in_description"] = book_missing["description"].str.split().str.len()
book_missing

book_missing.loc[book_missing["words_in_description"].between(5, 14), "description"]
book_missing.loc[book_missing["words_in_description"].between(15, 24), "description"]
book_missing.loc[book_missing["words_in_description"].between(25, 34), "description"]
book_missing_25_words = book_missing[book_missing["words_in_description"] >= 25]
book_missing_25_words

book_missing_25_words["title_and_subtitle"] = (
    np.where(book_missing_25_words["subtitle"].isna(), book_missing_25_words["title"],
             book_missing_25_words[["title", "subtitle"]].astype(str).agg(": ".join, axis=1))
)

book_missing_25_words

book_missing_25_words["tagged_description"] = book_missing_25_words[["isbn13", "description"]].astype(str).agg(" ".join, axis=1)
(
    book_missing_25_words
    .drop(["subtitle", "missing_description", "age_of_book", "words_in_description"], axis=1)
    .to_csv("books_cleaned.csv", index = False)
)

!pip install langchain-community langchain-openai langchain-chroma langchain-text-splitters python-dotenv

from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma
from dotenv import load_dotenv

with open(".env", "w") as f:
    f.write("OPENAI_API_KEY=key")

load_dotenv()
import os
print(os.getenv("OPENAI_API_KEY"))

import pandas as pd

books = pd.read_csv("books_cleaned.csv")

books["tagged_description"].to_csv("tagged_description.txt",
                                   sep = "\n",
                                   index = False,
                                   header = False)

raw_documents = TextLoader("tagged_description.txt").load()
text_splitter = CharacterTextSplitter(chunk_size=0, chunk_overlap=0, separator="\n")
documents = text_splitter.split_documents(raw_documents)

db_books = Chroma.from_documents(
    documents,
    embedding=OpenAIEmbeddings())
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k = 10)
docs

books[books["isbn13"] == int(docs[0].page_content.split()[0].strip())]

def retrieve_semantic_recommendations(
        query: str,
        top_k: int = 10,
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k = 50)

    books_list = []

    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)]

!pip install transformers

from transformers import pipeline

book_categories = [
    "Fiction",
    "Nonfiction",
]

import pandas as pd
import torch
from transformers import pipeline

device = 0 if torch.cuda.is_available() else -1
books = pd.read_csv("books_cleaned.csv")

summarizer = pipeline("summarization", model="facebook/bart-large-cnn", device=device)
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli", device=device)

from tqdm import tqdm
from transformers import pipeline

books_copy = books.copy()
batch_size = 8
descriptions = books_copy['description'].tolist()
predicted_classes = []

for i in tqdm(range(0, len(descriptions), batch_size), desc="Batch classifying"):
    batch = descriptions[i:i+batch_size]
    try:
        results = classifier(batch, book_categories)
        for result in results:
            predicted_classes.append(result['labels'][0])
    except Exception:
        predicted_classes += ["Unknown"] * len(batch)
books_copy['predicted_class'] = predicted_classes

final_df = books_copy[['title', 'authors', 'description', 'thumbnail', 'predicted_class']]
final_df = final_df.rename(columns={'predicted_class': 'category'})
final_df.to_csv("classified_books_sample.csv", index=False)

print(" File saved as 'classified_books_sample.csv'")

import gradio as gr

books_full = pd.read_csv("books_cleaned.csv")


classified = pd.read_csv("classified_books_sample.csv")

books = pd.merge(books_full, classified[["title", "category"]], on="title", how="left")


books["large_thumbnail"] = books["thumbnail"] + "&fife=w800"
books["large_thumbnail"] = np.where(
    books["large_thumbnail"].isna(),
    "cover-not-found.jpg",
    books["large_thumbnail"]
)


raw_documents = TextLoader("tagged_description.txt").load()
text_splitter = CharacterTextSplitter(separator="\n", chunk_size=0, chunk_overlap=0)
documents = text_splitter.split_documents(raw_documents)
db_books = Chroma.from_documents(documents, OpenAIEmbeddings())

def retrieve_semantic_recommendations(query: str, category: str = "All", top_k: int = 16):
    recs = db_books.similarity_search(query, k=50)
    isbn_list = [int(rec.page_content.strip('"').split()[0]) for rec in recs]
    book_recs = books[books["isbn13"].isin(isbn_list)]

    if category != "All":
        book_recs = book_recs[book_recs["category"] == category]

    return book_recs.head(top_k)


def recommend_books(query: str, category: str):
    recommendations = retrieve_semantic_recommendations(query, category)
    results = []

    for _, row in recommendations.iterrows():
        short_desc = " ".join(row["description"].split()[:30]) + "..."

        authors_split = row["authors"].split(";")
        if len(authors_split) == 2:
            author_str = f"{authors_split[0]} and {authors_split[1]}"
        elif len(authors_split) > 2:
            author_str = f"{', '.join(authors_split[:-1])}, and {authors_split[-1]}"
        else:
            author_str = row["authors"]

        caption = f"{row['title']} by {author_str}: {short_desc}"
        results.append((row["large_thumbnail"], caption))

    return results


categories = ["All"] + sorted(books["category"].dropna().unique())


with gr.Blocks(theme=gr.themes.Glass()) as dashboard:
    gr.Markdown("## 📘 Book Recommender")

    with gr.Row():
        user_query = gr.Textbox(label="Describe the book you're looking for:",
                                placeholder="e.g. A dark mystery about revenge")
        category_dropdown = gr.Dropdown(choices=categories, label="Pick a category", value="All")
        submit_button = gr.Button("Recommend")

    gr.Markdown("### 🔍 Your Matches")
    output = gr.Gallery(label="Results", columns=4, rows=2)

    submit_button.click(fn=recommend_books,
                        inputs=[user_query, category_dropdown],
                        outputs=output)

if __name__ == "__main__":
    dashboard.launch()

categories = ["All"] + sorted(books["category"].dropna().unique())

with gr.Blocks(theme=gr.themes.Glass()) as dashboard:
    gr.Markdown(" Semantic Book Recommender")

    with gr.Row():
        user_query = gr.Textbox(label="Describe the kind of book you want:",
                                placeholder="e.g., A story about survival and redemption")
        category_dropdown = gr.Dropdown(choices=categories, label="Choose a category:", value="All")
        submit_button = gr.Button("Recommend Books")

    gr.Markdown(" Recommendations")
    output = gr.Gallery(label="Top Matches", columns=4, rows=2)

    submit_button.click(fn=recommend_books, inputs=[user_query, category_dropdown], outputs=output)

if __name__ == "__main__":
    dashboard.launch()

while True:
    pass

